name: Release to Maven Central Repository
on:
    pull_request:
jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            MAVEN_USERNAME: ${{ secrets.DATAVERSEBOT_SONATYPE_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.DATAVERSEBOT_SONATYPE_TOKEN }}
            MAVEN_GPG_PASSPHRASE: ${{ secrets.DATAVERSEBOT_GPG_PASSWORD }}
        steps:
            - uses: actions/checkout@v2
            - name: Set up Maven Central Repository
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'
                  server-id: ossrh
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  gpg-private-key: ${{ secrets.DATAVERSEBOT_GPG_KEY }}
                  gpg-passphrase: MAVEN_GPG_PASSPHRASE
            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            - name: Build, test, verify
              run: |
                    cat /home/runner/.m2/settings.xml
                    mvn -B verify
            #- name: Check POM metadata for release
            #  run: mvn pomchecker:check-maven-central
            - name: Sign release
              run: |
                    cat /home/runner/.m2/settings.xml
                    mvn -Prelease verify -DskipAnalysis -DskipUT -DskipIT