name: Snapshot to Maven Central Repository
on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, '[maven-release-plugin]') }}
        steps:
            - uses: actions/checkout@v2
            - name: Set up Maven Central Repository
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'
                  server-id: ossrh
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            - name: Build, test, verify and publish snapshot
              run: mvn --batch-mode verify
            - name: Publish snapshot
              run: mvn --batch-mode deploy -DskipAnalysis -DskipUT -DskipIT
              env:
                  MAVEN_USERNAME: ${{ secrets.DATAVERSEBOT_SONATYPE_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.DATAVERSEBOT_SONATYPE_TOKEN }}